name: main

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@0.1.0
        with:
          silent: false
          verbose: true
          disable-auto-clean: false
